name: vscode-server
on:
  workflow_dispatch:
    inputs:
      gh-user:
        description: 'GitHub user name'
        required: true
        default: 'dirkarnez'
        type: string # Supported types: string, choice, boolean, environment
      gh-repo:
        description: 'GitHub repository'
        required: true
        type: string # Supported types: string, choice, boolean, environment
      repo-ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        default: 'main'
        type: string # Supported types: string, choice, boolean, environment

permissions:
    contents: write
    actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/checkout@v6
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: '${{ github.event.inputs.gh-user }}/${{ github.event.inputs.gh-repo }}'
          path: '${{ github.event.inputs.gh-repo }}'
          token: '${{ secrets.GH_PAT }}' # `GH_PAT` is a secret that contains your PAT
          ref: '${{ github.event.inputs.repo-ref }}' # The branch, tag or SHA to checkout
          
      - run: |
          git config --global user.name "dirkarnez" && \
          git config --global user.email "smalldirkalex@gmail.com" && \
          git config --global core.fileMode false
          
      - run: |
          sudo chmod -R +x . && \
          ls
      
    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, uses the default branch.

      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        with:
          timeout: '999999999'       # optional, default: 30000
