name: vscode-server
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        default: 'ubuntu-latest'
        options:
        - windows-latest
        - ubuntu-latest
        - macos-latest
      gh-user:
        description: 'GitHub user name'
        required: true
        default: 'dirkarnez'
        type: string # Supported types: string, choice, boolean, environment
      gh-repo:
        description: 'GitHub repository'
        required: true
        type: string # Supported types: string, choice, boolean, environment
      install-rust:
        description: 'Install Rust?'
        required: true
        type: boolean
        default: false
      install-python:
        description: 'Install Python?'
        required: true
        type: boolean
        default: false
      install-node:
        description: 'Install Node.js?'
        required: true
        type: boolean
        default: false
      install-go:
        description: 'Install Go?'
        required: true
        type: boolean
        default: false
      repo-ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        default: 'main'
        type: string # Supported types: string, choice, boolean, environment

permissions:
    contents: write
    actions: read

jobs:
  build:
    runs-on: [ "${{ github.event.inputs.chosen-os }}" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/checkout@v6
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: '${{ github.event.inputs.gh-user }}/${{ github.event.inputs.gh-repo }}'
          path: '${{ github.event.inputs.gh-repo }}'
          token: '${{ secrets.GH_PAT }}' # `GH_PAT` is a secret that contains your PAT
          ref: '${{ github.event.inputs.repo-ref }}' # The branch, tag or SHA to checkout
          
      - shell: bash
        run: |
          git config --global user.name "dirkarnez" && \
          git config --global user.email "smalldirkalex@gmail.com" && \
          git config --global core.fileMode false && \
          git config --global core.autocrlf false

      - shell: bash
        run: |
          git config core.fileMode false && \
          git config core.autocrlf false

      - working-directory: '${{ github.event.inputs.gh-repo }}'
        shell: bash
        run: |
          git config core.fileMode false && \
          git config core.autocrlf false
          
      - shell: bash
        if: ${{ github.event.inputs.chosen-os != 'windows-latest' }}
        run: |
          sudo chmod -R +x . && \
          ls
          
      - if: ${{ inputs.install-rust == true }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        
      - if: ${{ inputs.install-python == true }}
        uses: actions/setup-python@v6

      - if: ${{ inputs.install-go == true }}
        uses: actions/setup-go@v6

      - if: ${{ inputs.install-node == true }}
        uses: actions/setup-node@v7

    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, uses the default branch.
    # cwd: '${{ github.event.inputs.gh-repo }}'
    
    # - if: ${{ github.event.inputs.chosen-os != 'windows-latest' }}
      - uses: stateful/vscode-server-action@main
        with:
          timeout: '21600000'       # optional, default: 30000. 6 hrs = 6 * 60 * 60 *  1000 
          
