name: vscode-server
on:
  workflow_dispatch:

permissions:
    contents: write
    actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        with:
          timeout: '999999999'       # optional, default: 30000
